version: 2.1

orbs:
  node: circleci/node@2.0.1

# ---

executors:
  bread-executor:
    parameters:
      tag:
        type: string
        default: 'latest'
    docker:
      - image: cimg/node:<<parameters.tag>>
    working_directory: ~/app

# ---

jobs:

  test:
    executor:
      name: bread-executor
      tag: '12.16.1'

    steps:
      - checkout
      - run: yarn --version
      - run: node --version

      - node/install-packages:
          app-dir: ~/app
          pkg-manager: yarn
          cache-key: yarn.lock

      - run:
          name: "Lerna Bootstrap"
          command: yarn bootstrap

      - run:
          name: "Build Packages"
          command: yarn build

      #      - run:
      #          name: "Check Types"
      #          command: yarn check-types

      - run:
          name: "Lint"
          command: yarn lint:ci

      - run:
          name: "Test"
          command: yarn test:ci

      # TODO: find out how to store artefacts for all packages automatically (like with wildcard)
      #      - store_test_results:
      #          path: packages/adapter-bamboo-hr/reports/junit
      #
      #      - store_artifacts:
      #          path: packages/adapter-bamboo-hr/reports/junit
      #          destination: test-results/adapter-bamboo-hr
      #
      #      - store_artifacts:
      #          path: packages/adapter-bamboo-hr/coverage
      #          destination: coverage/adapter-bamboo-hr

workflows:
  test:
    jobs:
      - test
